SELECT CASE 
    WHEN S1.PLAYER IS NOT NULL
        THEN S1.PLAYER
        WHEN S1.PLAYER IS NULL
            THEN COALESCE(S2.PLAYER,S3.PLAYER)
            WHEN S2.PLAYER IS NULL
                THEN COALESCE(S3.PLAYER,S4.PLAYER)
                WHEN S3.PLAYER IS NULL
                    THEN COALESCE(S4.PLAYER,S3.PLAYER)
    ELSE COALESCE(S2.PLAYER,S1.PLAYER)
END as NAME,
COALESCE(S1.TD,0) AS TD1,COALESCE(S2.TD,0) AS TD2,
COALESCE(S3.TD,0) AS TD3,COALESCE(S4.TD,0) AS TD4,
(COALESCE(S1.TD,0)+COALESCE(S2.TD,0)+COALESCE(S3.TD,0)+COALESCE(S4.TD,0)) AS TOTAL_TD FROM NFL.S2011 AS S1
LEFT JOIN NFL.S2014 AS S4
ON S4.PLAYER = S1.PLAYER
LEFT JOIN NFL.S2012 AS S2
ON S2.PLAYER = S4.PLAYER
LEFT JOIN NFL.S2013 AS S3
ON S3.PLAYER = S2.PLAYER

UNION

SELECT CASE 
    WHEN S1.PLAYER IS NOT NULL
        THEN S1.PLAYER
        WHEN S1.PLAYER IS NULL
            THEN COALESCE(S2.PLAYER,S3.PLAYER)
            WHEN S2.PLAYER IS NULL
                THEN COALESCE(S3.PLAYER,S4.PLAYER)
                WHEN S3.PLAYER IS NULL
                    THEN COALESCE(S4.PLAYER,S3.PLAYER)
    ELSE COALESCE(S2.PLAYER,S1.PLAYER)
END as NAME,
COALESCE(S1.TD,0) AS TD1,COALESCE(S2.TD,0) AS TD2,
COALESCE(S3.TD,0) AS TD3, COALESCE(S4.TD,0) AS TD4,
(COALESCE(S1.TD,0)+COALESCE(S2.TD,0)+COALESCE(S3.TD,0)+COALESCE(S4.TD,0)) AS TOTAL_TD FROM NFL.S2011 AS S1
RIGHT JOIN NFL.S2014 AS S4
ON S4.PLAYER = S1.PLAYER
RIGHT JOIN NFL.S2012 AS S2
ON S2.PLAYER = S4.PLAYER
RIGHT JOIN NFL.S2013 AS S3
ON S3.PLAYER = S2.PLAYER


#WHERE S1.TD>25 OR S2.TD>25 OR S3.TD>25 OR S4.TD>25 OR S5.TD>25 OR S5.TD>25 OR S7.TD>25 OR S8.TD>25 OR S9.TD>25 OR S10.TD>25 OR S11.TD>25
ORDER BY TOTAL_TD DESC
