SELECT CASE 
    WHEN S1.NAME IS NOT NULL
        THEN S1.NAME
        WHEN S1.NAME IS NULL
            THEN COALESCE(S2.NAME,S3.NAME)
            WHEN S2.NAME IS NULL
                THEN COALESCE(S3.NAME,S2.NAME)
    ELSE COALESCE(S1.NAME,S1.NAME)
END as NAME,
COALESCE(S1.TOTAL_TD,0) AS TD11_14,COALESCE(S2.TOTAL_TD,0) AS TD15_18,
COALESCE(S3.TOTAL_TD,0) AS TD19_21,
(COALESCE(S1.TOTAL_TD,0)+COALESCE(S2.TOTAL_TD,0)+COALESCE(S3.TOTAL_TD,0)) AS TOTAL_TD FROM NFL.TD2011 AS S1
LEFT JOIN NFL.TD2015 AS S2
ON S2.NAME = S1.NAME
LEFT JOIN NFL.TD2019 AS S3
ON S3.NAME = S2.NAME
GROUP BY NAME

#HAVING TOTAL_TD > 5

UNION

SELECT CASE 
    WHEN S1.NAME IS NOT NULL
        THEN S1.NAME
        WHEN S1.NAME IS NULL
            THEN COALESCE(S2.NAME,S3.NAME)
            WHEN S2.NAME IS NULL
                THEN COALESCE(S3.NAME,S2.NAME)
    ELSE COALESCE(S1.NAME,S1.NAME)
END as NAME,
COALESCE(S1.TOTAL_TD,0) AS TD11_14,COALESCE(S2.TOTAL_TD,0) AS TD15_18,
COALESCE(S3.TOTAL_TD,0) AS TD19_21,
(COALESCE(S1.TOTAL_TD,0)+COALESCE(S2.TOTAL_TD,0)+COALESCE(S3.TOTAL_TD,0)) AS TOTAL_TD FROM NFL.TD2011 AS S1
RIGHT JOIN NFL.TD2015 AS S2
ON S2.NAME = S1.NAME
RIGHT JOIN NFL.TD2019 AS S3
ON S3.NAME = S2.NAME
GROUP BY NAME


#HAVING TOTAL_TD > 5
ORDER BY TOTAL_TD DESC
